/**
 * ICS 日历文件生成器
 * 
 * 功能：
 * - 生成符合 RFC5545 标准的 ICS 文件
 * - 支持全天事件
 * - 支持提醒功能
 * - 支持多语言事件描述
 */

import { format } from 'date-fns';

interface ICSEventOptions {
  title: string;
  date: Date;
  description?: string;
  reminder?: boolean; // 是否添加提前1天提醒
  locale?: string;
}

/**
 * 格式化日期为 ICS 格式 (YYYYMMDD)
 */
function formatICSDate(date: Date): string {
  return format(date, 'yyyyMMdd');
}

/**
 * 格式化日期时间为 ICS 格式 (YYYYMMDDTHHmmss)
 */
function formatICSDateTime(date: Date): string {
  return format(date, "yyyyMMdd'T'HHmmss");
}

/**
 * 生成唯一ID
 */
function generateUID(): string {
  return `${Date.now()}-${Math.random().toString(36).substring(2, 9)}@daysfromtoday.ai`;
}

/**
 * 转义 ICS 文本内容
 */
function escapeICSText(text: string): string {
  return text
    .replace(/\\/g, '\\\\')
    .replace(/;/g, '\\;')
    .replace(/,/g, '\\,')
    .replace(/\n/g, '\\n');
}

/**
 * 生成 ICS 日历文件内容
 */
export function generateICS(options: ICSEventOptions): string {
  const { title, date, description, reminder = true } = options;
  
  const eventDate = formatICSDate(date);
  const now = formatICSDateTime(new Date());
  const uid = generateUID();
  
  // 构建 ICS 内容
  const icsContent = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//DaysFromToday//Date Calculator//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    'BEGIN:VEVENT',
    `UID:${uid}`,
    `DTSTAMP:${now}`,
    `DTSTART;VALUE=DATE:${eventDate}`,
    `DTEND;VALUE=DATE:${eventDate}`,
    `SUMMARY:${escapeICSText(title)}`,
    description ? `DESCRIPTION:${escapeICSText(description)}` : null,
    'STATUS:CONFIRMED',
    'TRANSP:TRANSPARENT',
    // 添加提醒（提前1天）
    reminder ? 'BEGIN:VALARM' : null,
    reminder ? 'ACTION:DISPLAY' : null,
    reminder ? `DESCRIPTION:${escapeICSText(title)}` : null,
    reminder ? 'TRIGGER:-P1D' : null, // 提前1天
    reminder ? 'END:VALARM' : null,
    'END:VEVENT',
    'END:VCALENDAR'
  ].filter(line => line !== null).join('\r\n');
  
  return icsContent;
}

/**
 * 下载 ICS 文件
 */
export function downloadICS(options: ICSEventOptions, filename?: string): void {
  const icsContent = generateICS(options);
  const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = filename || `event-${formatICSDate(options.date)}.ics`;
  
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  
  URL.revokeObjectURL(url);
}

/**
 * 生成日期计算事件的 ICS 文件
 */
export function generateDateCalculationICS(
  days: number,
  targetDate: Date,
  type: 'future' | 'past',
  mode: 'calendar' | 'business'
): string {
  const text = {
    en: {
      future: (d: number) => `${d} ${d === 1 ? 'day' : 'days'} from today`,
      past: (d: number) => `${d} ${d === 1 ? 'day' : 'days'} ago`,
      calendar: 'Calendar days',
      business: 'Business days',
      description: (type: string, mode: string, date: string) => 
        `This is ${days} ${mode} ${type} from today. Target date: ${date}. Generated by DaysFromToday.ai`
    },
    zh: {
      future: (d: number) => `从今天起 ${d} 天后`,
      past: (d: number) => `从今天起 ${d} 天前`,
      calendar: '自然日',
      business: '工作日',
      description: (type: string, mode: string, date: string) => 
        `这是从今天起${days}${mode}${type}的日期。目标日期：${date}。由 DaysFromToday.ai 生成`
    }
  };
  
  const t = text.en; // 默认使用英文
  const typeText = type === 'future' ? t.future(days) : t.past(days);
  const modeText = mode === 'calendar' ? t.calendar : t.business;
  const dateText = format(targetDate, 'MMM d, yyyy');
  
  const title = `${typeText} - ${dateText}`;
  const description = t.description(
    type === 'future' ? 'from today' : 'ago',
    modeText,
    dateText
  );
  
  return generateICS({
    title,
    date: targetDate,
    description,
    reminder: true
  });
}

/**
 * 下载日期计算事件的 ICS 文件
 */
export function downloadDateCalculationICS(
  days: number,
  targetDate: Date,
  type: 'future' | 'past',
  mode: 'calendar' | 'business'
): void {
  const icsContent = generateDateCalculationICS(days, targetDate, type, mode);
  const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  
  const filename = `${days}-${mode === 'calendar' ? 'days' : 'business-days'}-${type}-${formatICSDate(targetDate)}.ics`;
  
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  
  URL.revokeObjectURL(url);
}
